name: Sync Daily Reports to Yuque

on:
  schedule:
    - cron: '15 1 * * *' # 每天北京时间9:15
  workflow_dispatch:

jobs:
  sync_yuque:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: 安装依赖
        run: npm install node-fetch

      - name: 同步日报到语雀
        env:
          YUQUE_TOKEN: ${{ secrets.YUQUE_TOKEN }}
        run: node scripts/pushToYuque.js